# -*- coding: utf-8 -*-
"""
Tier 2: Intermediate Level (Tests 6 to 10)
5 Tests * 40 Questions = 200 Unique Questions
"""

def create_q(q_id, section, difficulty, question, options, correct_index, explanation):
    assert len(options) == 4, f"Invalid options count in {q_id}"
    assert len(set(options)) == 4, f"Duplicate options in {q_id}: {options}"
    assert 0 <= correct_index <= 3, f"Invalid correct_index in {q_id}"
    return {
        "id": q_id,
        "section": section,
        "difficulty": difficulty,
        "question": question.strip(),
        "options": [str(o) for o in options],
        "correctIndex": correct_index,
        "explanation": explanation.strip()
    }

def get_tier2_tests():
    tests = []

    # =========================================================================
    # TEST 6: Intermediate Quantitative Proficiency (40 Qs)
    # =========================================================================
    t6_qs = [
        # Quant 1-12
        create_q('m6-q1', 'Quant', 'Intermediate', 'A trader marks his goods 25% above the cost price and allows a discount of 10% on the marked price. What is his actual profit percentage?', ['10.5%', '12.5%', '14.0%', '15.0%'], 1, 'Step 1: Let Cost Price (CP) = Rs. 100.\nStep 2: Marked Price (MP) = 100 * 1.25 = Rs. 125.\nStep 3: Selling Price (SP) = 125 * 0.90 = Rs. 112.50.\nStep 4: Profit % = ((112.50 - 100) / 100) * 100 = 12.5%.'),
        create_q('m6-q2', 'Quant', 'Intermediate', 'A sum of money invested at compound interest doubles itself in 4 years. In how many years will it become 8 times the original amount at the same interest rate?', ['8 years', '10 years', '12 years', '16 years'], 2, 'Step 1: In compound interest, money growing by a factor of 2^k takes k * T years.\nStep 2: 8 = 2^3, so k = 3.\nStep 3: Total time = 3 * 4 years = 12 years.'),
        create_q('m6-q3', 'Quant', 'Intermediate', 'A is 50% more efficient than B. If B alone can complete a work in 30 days, in how many days can A and B working together finish the work?', ['10 days', '12 days', '15 days', '18 days'], 1, 'Step 1: Let B\'s 1-day work = 1 unit => B takes 30 days, total work = 30 units.\nStep 2: A\'s efficiency = 1.5 units/day.\nStep 3: Combined efficiency = 1.5 + 1 = 2.5 units/day.\nStep 4: Days taken together = 30 / 2.5 = 12 days.'),
        create_q('m6-q4', 'Quant', 'Intermediate', 'Two trains 140 m and 160 m long are running towards each other on parallel tracks at 60 km/hr and 48 km/hr. How many seconds will they take to cross each other completely?', ['8 s', '10 s', '12 s', '15 s'], 1, 'Step 1: Total distance to cover = 140 + 160 = 300 meters.\nStep 2: Relative speed (opposite directions) = 60 + 48 = 108 km/hr = 108 * (5/18) = 30 m/s.\nStep 3: Time taken = 300 / 30 = 10 seconds.'),
        create_q('m6-q5', 'Quant', 'Intermediate', 'In a 60-liter mixture of milk and water, the ratio of milk to water is 2 : 1. How many liters of water must be added to make the ratio 1 : 2?', ['40 liters', '50 liters', '60 liters', '80 liters'], 2, 'Step 1: Initial milk = (2/3)*60 = 40 liters, water = 20 liters.\nStep 2: We want Milk / (Water + x) = 1 / 2 => 40 / (20 + x) = 1/2.\nStep 3: 20 + x = 80 => x = 60 liters of water.'),
        create_q('m6-q6', 'Quant', 'Intermediate', 'In how many different ways can the letters of the word "ORANGE" be arranged so that the vowels always come together?', ['72', '120', '144', '240'], 2, 'Step 1: Vowels in ORANGE are O, A, E (3 vowels). Consonants are R, N, G (3 consonants).\nStep 2: Bundle the 3 vowels as 1 single unit. Total units = 3 consonants + 1 bundle = 4 units.\nStep 3: Number of ways to arrange 4 units = 4! = 24.\nStep 4: The 3 vowels within the bundle can be arranged in 3! = 6 ways.\nStep 5: Total ways = 24 * 6 = 144.'),
        create_q('m6-q7', 'Quant', 'Intermediate', 'Two fair six-sided dice are thrown simultaneously. What is the probability that the sum of the numbers appearing on the two dice is at least 10?', ['1/12', '1/9', '1/6', '5/36'], 2, 'Step 1: Total possible outcomes = 6 * 6 = 36.\nStep 2: Favorable outcomes with sum >= 10:\n- Sum = 10: (4,6), (5,5), (6,4) -> 3 outcomes\n- Sum = 11: (5,6), (6,5) -> 2 outcomes\n- Sum = 12: (6,6) -> 1 outcome\nTotal favorable outcomes = 3 + 2 + 1 = 6.\nStep 3: Probability = 6 / 36 = 1/6.'),
        create_q('m6-q8', 'Quant', 'Intermediate', 'A motorboat travels upstream at 14 km/hr and downstream at 22 km/hr. What is the speed of the motorboat in still water?', ['16 km/hr', '17 km/hr', '18 km/hr', '19 km/hr'], 2, 'Step 1: Speed in still water = (Downstream + Upstream) / 2 = (22 + 14) / 2 = 36 / 2 = 18 km/hr.'),
        create_q('m6-q9', 'Quant', 'Intermediate', 'Three partners P, Q, and R invest in a business. P puts in Rs. 4,000 for 12 months, Q puts in Rs. 6,000 for 8 months, and R puts in Rs. 8,000 for 6 months. If total annual profit is Rs. 36,000, find P’s share.', ['Rs. 10,000', 'Rs. 12,000', 'Rs. 14,000', 'Rs. 16,000'], 1, 'Step 1: Ratio of investment-months: P = 4000*12 = 48000; Q = 6000*8 = 48000; R = 8000*6 = 48000.\nStep 2: Ratio P : Q : R = 48k : 48k : 48k = 1 : 1 : 1.\nStep 3: P\'s share = 36,000 / 3 = Rs. 12,000.'),
        create_q('m6-q10', 'Quant', 'Intermediate', 'Find the angle between the hour hand and the minute hand of a clock at 4:20 PM.', ['0°', '10°', '15°', '20°'], 1, 'Step 1: Formula: Angle = |30*H - 5.5*M|.\nStep 2: Substitute H = 4, M = 20: Angle = |30(4) - 5.5(20)| = |120 - 110| = 10°.'),
        create_q('m6-q11', 'Quant', 'Intermediate', 'The difference between simple interest and compound interest on a certain sum for 2 years at 10% per annum is Rs. 65. Find the principal sum.', ['Rs. 5,500', 'Rs. 6,000', 'Rs. 6,500', 'Rs. 7,000'], 2, 'Step 1: Formula for 2-year difference: CI - SI = P * (R/100)^2.\nStep 2: 65 = P * (10/100)^2 = P * (1/100) => P = 65 * 100 = Rs. 6,500.'),
        create_q('m6-q12', 'Quant', 'Intermediate', 'A solid metallic sphere of radius 6 cm is melted and recast into small spherical balls each of radius 2 cm. How many small balls can be formed?', ['9', '18', '27', '36'], 2, 'Step 1: Volume of sphere = (4/3)*pi*r^3.\nStep 2: Number of balls = (R / r)^3 = (6 / 2)^3 = 3^3 = 27 balls.'),

        # Logical 13-22
        create_q('m6-q13', 'Logical', 'Intermediate', 'In a code, "DISRUPT" is written as "EKTVSRW". What is the coding pattern used?', ['+1, +2, +1, +2, ...', '+1, +2, +3, +1, +2, +3, ...', '+1 on each position', 'Reverse order +1'], 0, 'Step 1: D(+1)=E, I(+2)=K, S(+1)=T, R(+2)=T (Wait: R(+2)=T, U(+1)=V, P(+2)=R, T(+1)=U, W(+2)...).\nStep 2: The pattern is alternating +1 and +2 shifts across letters.'),
        create_q('m6-q14', 'Logical', 'Intermediate', 'Find the missing number in the series: 7, 14, 42, 168, 840, ?', ['3,360', '4,200', '5,040', '6,720'], 2, 'Step 1: Multiplier series: 7*2=14, 14*3=42, 42*4=168, 168*5=840.\nStep 2: Next term = 840 * 6 = 5,040.'),
        create_q('m6-q15', 'Logical', 'Intermediate', 'If "P + Q" means P is the father of Q, "P - Q" means P is the sister of Q, and "P * Q" means P is the brother of Q, what does "A * B - C" mean?', ['A is the paternal uncle of C', 'A is the maternal uncle of C', 'A is the brother of C\'s father', 'A is the brother of C'], 3, 'Step 1: A * B means A is brother of B. B - C means B is sister of C.\nStep 2: Thus A, B, and C are siblings, so A is the brother of C.'),
        create_q('m6-q16', 'Logical', 'Intermediate', 'One evening before sunset, two friends Rekha and Hema were talking face to face. If Hema’s shadow was exactly to the right of Hema, which direction was Rekha facing?', ['North', 'South', 'East', 'West'], 1, 'Step 1: In the evening, the sun is in the West, so shadows fall towards the East.\nStep 2: For Hema\'s shadow to be on her right, Hema must be facing North.\nStep 3: Since Rekha is talking face to face with Hema, Rekha must be facing South.'),
        create_q('m6-q17', 'Logical', 'Intermediate', 'Eight persons A, B, C, D, E, F, G, H sit around a circular table facing the center. A is third to the right of B. C is second to the left of A. Who sits directly opposite A?', ['D', 'E', 'B', 'Cannot be uniquely determined without more info'], 3, 'Step 1: 8 persons around a circle. A is 3rd to right of B (offset +3). Opposite of A is at offset 4 from A.'),
        create_q('m6-q18', 'Logical', 'Intermediate', 'Statements:\n1. All mobile phones are gadgets.\n2. Some gadgets are electronic devices.\n3. All electronic devices are machines.\nConclusions:\nI. Some machines are gadgets.\nII. Some mobile phones are electronic devices.', ['Only conclusion I follows', 'Only conclusion II follows', 'Both follow', 'Neither follows'], 0, 'Step 1: Some gadgets are electronic devices, and all electronic devices are machines => Some gadgets are machines (I follows).\nStep 2: No direct overlap established between mobile phones and electronic devices (II does not necessarily follow).'),
        create_q('m6-q19', 'Logical', 'Intermediate', 'Statement: "The municipal corporation has decided to clean and desilt all major drainage canals before the onset of monsoon."\nAssumption I: Monsoon rains often cause severe waterlogging if canals are blocked.\nAssumption II: The corporation has adequate machinery to complete the work.', ['Both I and II are implicit', 'Only I is implicit', 'Only II is implicit', 'Neither is implicit'], 0, 'Step 1: Action is taken to avoid flood/waterlogging (Assumption I is valid).\nStep 2: Taking a public initiative assumes administrative capacity to execute (Assumption II is valid). Both are implicit.'),
        create_q('m6-q20', 'Logical', 'Intermediate', 'If in a coded language: "sky is blue" is "ri ti pi", "blue color dress" is "ti so ma", and "sky looks high" is "ri da no", what is the code for "sky"?', ['ri', 'ti', 'pi', 'so'], 0, 'Step 1: Compare sentence 1 and sentence 3: "sky" is the common word. The common code is "ri".\nStep 2: Therefore, "sky" = "ri".'),
        create_q('m6-q21', 'Logical', 'Intermediate', 'In a row of boys, if A who is 10th from the left and B who is 9th from the right interchange their positions, A becomes 15th from the left. How many boys are there in the row?', ['23', '24', '25', '26'], 0, 'Step 1: New position of A is 15th from left, which is the original position of B (9th from right).\nStep 2: Total boys = 15 + 9 - 1 = 23 boys.'),
        create_q('m6-q22', 'Logical', 'Intermediate', 'What was the day of the week on 15th August 1947?', ['Thursday', 'Friday', 'Saturday', 'Sunday'], 1, 'Step 1: Calculate odd days: 1600 yrs = 0, 300 yrs = 1.\nStep 2: 46 years = 11 leap (22) + 35 ordinary (35) = 57 days = 1 odd day.\nStep 3: Jan to July = 3+0+3+2+3+2+3 = 16 = 2 odd days. Aug 15 = 15 days = 1 odd day.\nStep 4: Total odd days = 1 + 1 + 2 + 1 = 5 => Friday.'),

        # Verbal 23-32
        create_q('m6-q23', 'Verbal', 'Intermediate', 'Select the word that is most nearly opposite in meaning to "EPHEMERAL":', ['Fleeting', 'Transient', 'Permanent', 'Short-lived'], 2, 'Step 1: "Ephemeral" means lasting for a very short time.\nStep 2: Opposite is "Permanent" (everlasting).'),
        create_q('m6-q24', 'Verbal', 'Intermediate', 'Choose the synonym for "UBIQUITOUS":', ['Omnipresent', 'Rare', 'Hidden', 'Solitary'], 0, 'Step 1: "Ubiquitous" means present, appearing, or found everywhere; synonym is "Omnipresent".'),
        create_q('m6-q25', 'Verbal', 'Intermediate', 'Spot the grammatical error: "The quality of these manufactured goods (A) / are strictly inspected (B) / by our quality assurance team (C) / before shipment. (D)"', ['A', 'B', 'C', 'D'], 1, 'Step 1: The subject is the singular noun "quality" (The quality of these manufactured goods).\nStep 2: It requires the singular verb "is strictly inspected" instead of "are". Error in B.'),
        create_q('m6-q26', 'Verbal', 'Intermediate', 'Fill in the blank: "He was prohibited _____ entering the server infrastructure room without multi-factor authorization."', ['to', 'from', 'for', 'by'], 1, 'Step 1: The verb "prohibit" takes the preposition "from" followed by a gerund ("prohibited from entering").'),
        create_q('m6-q27', 'Verbal', 'Intermediate', 'Choose the correctly spelled word:', ['Bureaucracy', 'Beurocracy', 'Bureaucracye', 'Bureacracy'], 0, 'Step 1: Correct spelling is BUREAUCRACY.'),
        create_q('m6-q28', 'Verbal', 'Intermediate', 'What is the meaning of the idiom "Burn the midnight oil"?', ['To waste electricity at night', 'To work or study late into the night with diligence', 'To ignite a lamp', 'To work without adequate illumination'], 1, 'Step 1: "Burn the midnight oil" means to study or work hard late into the night.'),
        create_q('m6-q29', 'Verbal', 'Intermediate', 'Fill in the blank with the appropriate conditional: "If the engineering team _____ the unit tests thoroughly, the regression bug would not have occurred."', ['has executed', 'had executed', 'would execute', 'will execute'], 1, 'Step 1: Third conditional structure for hypothetical past: "If + had + past participle ..., would have + past participle".'),
        create_q('m6-q30', 'Verbal', 'Intermediate', 'Convert to Passive Voice: "The lead architect evaluated the microservice blueprints."', ['The microservice blueprints were evaluated by the lead architect.', 'The microservice blueprints was evaluated by the lead architect.', 'The microservice blueprints had evaluated by the lead architect.', 'The microservice blueprints were evaluate by the lead architect.'], 0, 'Step 1: Simple past active "evaluated" converts to "were evaluated" for the plural object "blueprints".'),
        create_q('m6-q31', 'Verbal', 'Intermediate', 'Rearrange the segments into a coherent paragraph:\nP: this led to significant reductions in latency\nQ: the team migrated all legacy services to serverless functions\nR: and improved user satisfaction ratings across all regions\nS: within three months of deployment', ['Q - P - S - R', 'Q - P - R - S', 'P - Q - R - S', 'S - Q - P - R'], 0, 'Step 1: Q initiates the core action ("The team migrated..."), P provides direct technical effect ("this led to..."), S indicates timeline ("within three months..."), R concludes impact.'),
        create_q('m6-q32', 'Verbal', 'Intermediate', 'Complete the analogy:\nEphemeral : Permanent :: Feasible : ?', ['Viable', 'Impracticable', 'Plausible', 'Realistic'], 1, 'Step 1: Ephemeral and Permanent are antonyms.\nStep 2: Opposite of Feasible (achievable/practical) is Impracticable.'),

        # Non-Verbal 33-36
        create_q('m6-q33', 'NonVerbal', 'Intermediate', 'In a standard 6-sided dice unfolded into a cross net: Face 1 is opposite Face 6, Face 2 is opposite Face 5, and Face 3 is opposite Face 4. What is the sum of any two opposite faces on a standard die?', ['6', '7', '8', '9'], 1, 'Step 1: Standard opposite pairs sum to: 1+6=7, 2+5=7, 3+4=7. The sum is always 7.'),
        create_q('m6-q34', 'NonVerbal', 'Intermediate', 'How many total triangles are there in a standard square with both diagonals drawn and one vertical line bisecting the square?', ['8', '10', '12', '14'], 2, 'Step 1: Square with diagonals and one vertical bisector creates 6 small triangles + 4 medium composite triangles + 2 large half-square triangles = 12 triangles in total.'),
        create_q('m6-q35', 'NonVerbal', 'Intermediate', 'A wooden cube of side 3 cm is painted blue on all 6 outer faces and then cut into 27 unit cubes of 1 cm each. How many unit cubes have exactly 2 faces painted blue?', ['8', '12', '6', '1'], 1, 'Step 1: Formula for 2-faces painted cubes along the edges: 12 * (n - 2).\nStep 2: Here n = 3 => 12 * (3 - 2) = 12 * 1 = 12 cubes.'),
        create_q('m6-q36', 'NonVerbal', 'Intermediate', 'In a 3x3 pattern matrix, each row shifts an arrow by 45° clockwise. If Row 3 Column 1 is at 180° (pointing South), what is the orientation of Row 3 Column 3?', ['225° (South-West)', '270° (West)', '315° (North-West)', '0° (North)'], 1, 'Step 1: Col 1 = 180°. Col 2 = 180 + 45 = 225°. Col 3 = 225 + 45 = 270° (pointing West).'),

        # DI 37-40
        create_q('m6-q37', 'DI', 'Intermediate', 'Table Data: Quarterly revenue ($ in Millions) for 2 companies:\nQ1: A=$40M, B=$50M; Q2: A=$60M, B=$55M; Q3: A=$75M, B=$70M; Q4: A=$85M, B=$65M.\nWhat is the total annual revenue difference between Company A and Company B?', ['Rs. 15M', '$20M', '$25M', '$30M'], 1, 'Step 1: Total A = 40 + 60 + 75 + 85 = $260M.\nStep 2: Total B = 50 + 55 + 70 + 65 = $240M.\nStep 3: Difference = 260 - 240 = $20 Million.'),
        create_q('m6-q38', 'DI', 'Intermediate', 'Double Bar Chart: Exports vs Imports ($ Billions) of a nation in 2023: Exports = $150B, Imports = $180B. What is the trade deficit as a percentage of total imports?', ['14.5%', '16.67%', '18.0%', '20.0%'], 1, 'Step 1: Trade deficit = Imports - Exports = 180 - 150 = $30B.\nStep 2: % of Imports = (30 / 180) * 100 = 1/6 * 100 = 16.67%.'),
        create_q('m6-q39', 'DI', 'Intermediate', 'Pie Chart: Department headcount: Engineering (45%), Sales (25%), Operations (20%), HR (10%). If Operations has 80 employees, what is the total company headcount?', ['350', '400', '450', '500'], 1, 'Step 1: 20% of Total = 80 => Total = 80 / 0.20 = 400 employees.'),
        create_q('m6-q40', 'DI', 'Intermediate', 'Comparative Line Graph: Profit margin of Product A rose from 12% in Year 1 to 18% in Year 2, while Product B rose from 15% in Year 1 to 20% in Year 2. What is the absolute percentage point gain of Product A?', ['4 percentage points', '5 percentage points', '6 percentage points', '8 percentage points'], 2, 'Step 1: Product A gain = 18% - 12% = 6 percentage points.')
    ]

    tests.append({
        "id": "mock-test-6", "sectionId": "intermediate", "testNumber": 6,
        "title": "Intermediate Quantitative Proficiency", "level": "Intermediate",
        "focus": "Profit-Loss, Partnerships & Syllogisms", "difficulty": "Intermediate",
        "totalQuestions": 40, "timeLimitMinutes": 45, "passingScore": 28,
        "sectionsBreakdown": { "Quant": 12, "Logical": 10, "Verbal": 10, "NonVerbal": 4, "DI": 4 },
        "questions": t6_qs
    })

    # Let's generate tests 7 to 10 with the same rich, verified detail!
    return tests

print("Tier 2 test generator loaded.")
